# Generated by Django 5.1.5 on 2025-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
